--Jawaban N0. 4 a
SELECT * FROM BARANG WHERE HARGA_SATUAN > 10000 ORDER BY HARGA_SATUAN;
--Jawaban N0. 4 b
SELECT * FROM PELANGGAN WHERE NAMA lIKE '%g%' AND ALAMAT = 'BANDUNG';
--Jawaban N0. 4 c
SELECT TRX.KODE, TRX.TANGGAL, PEL.NAMA AS NAMA_PELANGGAN, BRG.NAMA AS NAMA_BARANG, 
TRX.JUMLAH_BARANG AS JUMLAH, BRG.HARGA_SATUAN,
TRX.JUMLAH_BARANG * BRG.HARGA_SATUAN AS TOTAL
FROM TRANSAKSI TRX INNER JOIN PELANGGAN PEL ON PEL.KODE = TRX.KODE_PELANGGAN
INNER JOIN BARANG BRG ON BRG.KODE = TRX.KODE_BARANG ORDER BY PEL.NAMA, TRX.TANGGAL;
--Jawaban N0. 4 d
SELECT PEL.NAMA AS NAMA_PELANGGAN, SUM(TRX.JUMLAH_BARANG) AS JUMLAH,
SUM(TRX.JUMLAH_BARANG * BRG.HARGA_SATUAN) AS TOTAL_HARGA
FROM TRANSAKSI TRX INNER JOIN PELANGGAN PEL ON PEL.KODE = TRX.KODE_PELANGGAN
INNER JOIN BARANG BRG ON BRG.KODE = TRX.KODE_BARANG GROUP BY PEL.NAMA ORDER BY PEL.NAMA;